SELECT 
    B.BOOK_NAME AS 書名,
    C.BOOK_CLASS_NAME AS 類別,
    E.USER_CNAME AS 借閱者,
    D.CODE_NAME AS 借閱狀態 
FROM  BOOK_LEND_RECORD A
INNER JOIN BOOK_DATA B
    ON A.BOOK_ID = B.BOOK_ID
INNER JOIN BOOK_CLASS C 
    ON B.BOOK_CLASS_ID = C.BOOK_CLASS_ID
INNER JOIN BOOK_CODE D 
    ON B.BOOK_STATUS = D.CODE_ID
INNER JOIN MEMBER_M E 
    ON B.BOOK_KEEPER = E.USER_ID;
